# Generated by Django 5.2.17 on 2026-09-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("municipio", models.CharField(blank=True, max_length=100)),
                ("sucursal", models.CharField(blank=True, max_length=150)),
                ("canal", models.CharField(blank=True, max_length=100)),
                ("territorio", models.CharField(blank=True, max_length=100)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "limite_credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("dias_credito", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="ModalidadPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Modalidad de pago",
                "verbose_name_plural": "Modalidades de pago",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("familia", models.CharField(blank=True, max_length=100)),
                ("unidad_medida", models.CharField(default="UND", max_length=20)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "costo",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("zona", models.CharField(blank=True, max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Rutas",
            },
        ),
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VENDEDOR", "Vendedor"),
                            ("COBRADOR", "Cobrador"),
                            ("REPARTIDOR", "Repartidor"),
                        ],
                        default="VENDEDOR",
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Vendedores",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=30, unique=True)),
                ("serie", models.CharField(blank=True, max_length=30)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estado_entrega",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("COMPLETA", "Completa"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "estado_factura",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("ANULADA", "Anulada")],
                        default="ACTIVA",
                        max_length=20,
                    ),
                ),
                (
                    "origen_importacion",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del archivo Excel del que se importó",
                        max_length=100,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="core.cliente",
                    ),
                ),
                (
                    "modalidad_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.modalidadpago",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision", "-numero_factura"],
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrega", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[("PARCIAL", "Parcial"), ("TOTAL", "Total")],
                        max_length=10,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("CONFIRMADA", "Confirmada"), ("ANULADA", "Anulada")],
                        default="CONFIRMADA",
                        max_length=20,
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas",
                        to="core.factura",
                    ),
                ),
                (
                    "repartidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entregas",
            },
        ),
        migrations.CreateModel(
            name="Consignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrega", models.DateField()),
                ("fecha_liquidacion", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTA", "Abierta"),
                            ("LIQUIDADA", "Liquidada"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="ABIERTA",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.cliente"
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignaciones",
                        to="core.factura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Consignaciones",
            },
        ),
        migrations.CreateModel(
            name="FacturaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_facturada",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "precio_lista",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cantidad_entregada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="core.factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.producto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de factura",
                "verbose_name_plural": "Líneas de factura",
            },
        ),
        migrations.CreateModel(
            name="EntregaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_entregada",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="core.entrega",
                    ),
                ),
                (
                    "factura_detalle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.facturadetalle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de entrega",
                "verbose_name_plural": "Líneas de entrega",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="modalidad_pago_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.modalidadpago",
            ),
        ),
        migrations.CreateModel(
            name="CarteraCobro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("VENCIDA", "Vencida"),
                            ("PAGADA", "Pagada"),
                            ("EN_MORA", "En mora"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="VIGENTE",
                        max_length=20,
                    ),
                ),
                (
                    "factura",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cartera",
                        to="core.factura",
                    ),
                ),
                (
                    "modalidad_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.modalidadpago",
                    ),
                ),
                (
                    "cobrador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartera de cobro",
                "verbose_name_plural": "Cartera de cobro",
            },
        ),
        migrations.CreateModel(
            name="PlanPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuota", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto_cuota", models.DecimalField(decimal_places=2, max_digits=14)),
                ("saldo_cuota", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADA", "Pagada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "cartera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuotas",
                        to="core.carteracobro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota de pago",
                "verbose_name_plural": "Plan de pagos",
                "unique_together": {("cartera", "numero_cuota")},
            },
        ),
        migrations.CreateModel(
            name="ConsignacionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_entregada",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "cantidad_vendida",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "cantidad_devuelta",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "consignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="core.consignacion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.producto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de consignación",
                "verbose_name_plural": "Líneas de consignación",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="ruta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.ruta",
            ),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("CHEQUE", "Cheque"),
                            ("TARJETA", "Tarjeta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=50)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cartera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="core.carteracobro",
                    ),
                ),
                (
                    "plan_pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.planpago",
                    ),
                ),
                (
                    "cobrador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pagos",
            },
        ),
    ]
