# Generated by Django 5.2.17 on 2026-09-23 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_superusuario_inicial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Vehículos",
            },
        ),
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_planeada",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "km_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "km_final",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANEADA", "Planeada"),
                            ("EN_RUTA", "En ruta"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="PLANEADA",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "REPARTIDOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas_como_conductor",
                        to="core.vendedor",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas",
                        to="core.ruta",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga",
                "verbose_name_plural": "Cargas",
                "ordering": ["-fecha_planeada", "-id"],
            },
        ),
        migrations.AddField(
            model_name="factura",
            name="carga",
            field=models.ForeignKey(
                blank=True,
                help_text="Carga (salida de reparto) a la que fue asignada esta factura",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas",
                to="core.carga",
            ),
        ),
    ]
