# Generated by Django 5.2.17 on 2026-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_vehiculo_carga_factura_carga"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="fecha_sugerida_entrega",
            field=models.DateField(
                blank=True,
                help_text="El planeador la define factura por factura; por defecto es un día después de la fecha de emisión.",
                null=True,
            ),
        ),
    ]
