# Generated by Django 5.2.17 on 2026-09-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_factura_fecha_sugerida_entrega"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaResponsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Área responsable",
                "verbose_name_plural": "Áreas responsables",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="cantidad_devuelta",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="MotivoDevolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "area_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="motivos_devolucion",
                        to="core.arearesponsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de devolución",
                "verbose_name_plural": "Motivos de devolución",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="entrega",
            name="motivo_devolucion_general",
            field=models.ForeignKey(
                blank=True,
                help_text="Motivo que aplica a toda la visita (por ejemplo, local cerrado o cliente sin dinero). Déjalo vacío si lo que se devolvió fue solo algunos productos con su propio motivo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entregas_con_motivo_general",
                to="core.motivodevolucion",
            ),
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="motivo_devolucion",
            field=models.ForeignKey(
                blank=True,
                help_text="Motivo de devolución específico de este producto, si aplica.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lineas_entrega",
                to="core.motivodevolucion",
            ),
        ),
    ]
