# Generated by Django 5.2.17 on 2026-10-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_carga_codigo_acceso_unico"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrega",
            name="documento_cliente",
            field=models.CharField(
                blank=True,
                choices=[("ORIGINAL", "Original"), ("COPIA", "Copia")],
                help_text="Si al cliente se le dejó la factura original o una copia (Cambio #15). Vacío cuando en la visita no se entregó nada.",
                max_length=10,
                verbose_name="Factura dejada al cliente",
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="documento_devolucion",
            field=models.CharField(
                blank=True,
                help_text="Número del documento de devolución que llena el repartidor cuando en esta visita se devolvió algo (Cambio #15).",
                max_length=30,
                verbose_name="N.º de documento de devolución",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="numero_recibo",
            field=models.CharField(
                blank=True,
                help_text="Número del recibo con el que el repartidor recibe el efectivo del cliente (Cambio #15). Solo aplica a pagos en efectivo.",
                max_length=30,
                verbose_name="N.º de recibo",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="forma_pago",
            field=models.CharField(
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TRANSFERENCIA", "Transferencia"),
                    ("CHEQUE", "Cheque"),
                    ("TARJETA", "Tarjeta"),
                    ("NOTA_CREDITO", "Nota de crédito"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Número de transferencia, cheque o voucher; si la forma de pago es nota de crédito, aquí va el número de la nota de crédito.",
                max_length=50,
            ),
        ),
    ]
