# Generated by Django 5.2.17 on 2026-10-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_cambio15_recibo_devolucion_documento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carga",
            name="cerrada_en",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Cerrada el"
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="cerrada_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargas_cerradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cerrada por",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="facturas_liberadas",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="Facturas que seguían sin visitar al cerrar la carga y que por eso salieron de ella (quedaron 'Sin carga asignada'). Se guardan aquí para que el reporte de cierre las siga mostrando.",
                related_name="cargas_que_la_liberaron",
                to="core.factura",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="observaciones_cierre",
            field=models.TextField(
                blank=True,
                help_text="Obligatoria cuando el dinero recibido no cuadra con el sistema.",
                verbose_name="Observaciones del cierre (oficina)",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="observaciones_repartidor",
            field=models.TextField(
                blank=True,
                help_text="Lo que escribe el repartidor al marcar 'Terminé mi ruta'.",
                verbose_name="Observaciones del repartidor",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="ruta_terminada_en",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Ruta terminada el"
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="carga",
            field=models.ForeignKey(
                blank=True,
                help_text="Carga en la que se hizo esta visita (Cambio #14). Se guarda aparte de la carga de la factura para que el cierre de una carga no cambie si la factura se mueve después a otra carga.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entregas",
                to="core.carga",
            ),
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="recibido_bodega",
            field=models.BooleanField(
                default=False,
                help_text="Se marca en el cierre de la carga cuando bodega recibe lo devuelto (Cambio #14).",
                verbose_name="Recibido en bodega",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="entrega",
            field=models.ForeignKey(
                blank=True,
                help_text="Visita de entrega en la que el repartidor recibió este pago (Cambio #14). Vacío si el pago se registró fuera de una entrega.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos",
                to="core.entrega",
            ),
        ),
        migrations.AlterField(
            model_name="carga",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PLANEADA", "Planeada"),
                    ("EN_RUTA", "En ruta"),
                    ("RUTA_TERMINADA", "Ruta terminada"),
                    ("CERRADA", "Cerrada"),
                ],
                default="PLANEADA",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CargaCuadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forma_pago", models.CharField(max_length=20)),
                (
                    "segun_sistema",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "recibido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuadre",
                        to="core.carga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuadre de dinero",
                "verbose_name_plural": "Cuadre de dinero",
                "unique_together": {("carga", "forma_pago")},
            },
        ),
    ]
