# Cambio #16 (paso 1 de 3): campos nuevos de la recepción en bodega. La
# casilla anterior "recibido_bodega" se conserva hasta el paso 3 para poder
# convertir sus datos en el paso 2.
# Generated by Django 5.2.17 on 2026-10-05 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_cambio14_backfill_entrega_carga"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carga",
            options={
                "ordering": ["-fecha_planeada", "-id"],
                "permissions": [
                    ("recibir_devoluciones", "Puede recibir devoluciones en bodega")
                ],
                "verbose_name": "Carga",
                "verbose_name_plural": "Cargas",
            },
        ),
        migrations.AddField(
            model_name="carga",
            name="devoluciones_recibidas_en",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Devoluciones recibidas el",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="devoluciones_recibidas_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargas_recibidas_en_bodega",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Devoluciones recibidas por",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="observaciones_bodega",
            field=models.TextField(
                blank=True,
                help_text="Obligatoria cuando lo recibido en bodega no coincide con lo reportado.",
                verbose_name="Observaciones de bodega",
            ),
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="recibido_inventario",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="Recibido a inventario",
            ),
        ),
        migrations.AddField(
            model_name="entregadetalle",
            name="recibido_merma",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="Recibido como merma",
            ),
        ),
    ]
