# Generated by Django 5.2.17 on 2026-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_cambio16_quitar_casilla_recibido"),
    ]

    operations = [
        migrations.AddField(
            model_name="carga",
            name="facturas_no_cargadas",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="Facturas que no se marcaron como cargadas y que por eso salieron de la carga al tocar 'Salir a ruta' (quedaron 'Sin carga asignada'). Se guardan para que el cierre las siga mostrando.",
                related_name="cargas_que_no_la_cargaron",
                to="core.factura",
            ),
        ),
        migrations.AddField(
            model_name="carga",
            name="salio_a_ruta_en",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Salió a ruta el"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cargada_en",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Cargada el"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cargada_por",
            field=models.CharField(
                blank=True, editable=False, max_length=150, verbose_name="Cargada por"
            ),
        ),
    ]
