# Generated by Django 5.2.17 on 2026-10-09 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_cambio17_marcar_rutas_en_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="costo_flete",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo de llevar esta factura en la unidad (C$), lo escribe el planeador.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Costo",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="paquetes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Paquetes"
            ),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="pide_paquetes_costo",
            field=models.BooleanField(
                default=False,
                help_text="Al planear una Carga con esta unidad, cada factura debe llevar paquetes y costo (Cambio #18).",
                verbose_name="Pide paquetes y costo",
            ),
        ),
    ]
